### ISSUE TITLE
`moveby` with `args.properties = ["prev"]` not work after last occurrence

### ISSUE THREAD

**Issue by diogo-rossi** [rioj7/select-by#11]
I put the following in my `keybinds.json`

```
    {
        "key": "ctrl+shift+pageup",  // or any other key combo
        "when": "editorTextFocus",
        "command": "moveby.regex",
        "args": {
            "regex": "###",
            "properties": ["prev"]
        }
    }
```
It goes correctly to previous `###` **before** the the last occurrence of `###`.
After the last occurrence of the regex, nothing hapens.

**Comment by rioj7** [comment]
@Diogo-Rossi  Nice catch, found a few other cases too. Try v1.5.1
