### ISSUE TITLE
Regex key-binding hangs SelectBy sub-system

### ISSUE THREAD

**Issue by NorthboundTrain** [rioj7/select-by#12]
VS Code: 1.56.2
SelectBy: 1.5.1
MacOS: 11.4

I found SelectBy because I wanted to move via whitespace boundaries, so given this line of text, with my cursor at the beginning of the line, I wanted to be able to move to the positions shown:

```
foo-bar-baz FooBarBaz FOO BAR BAZ
           ^         ^   ^   ^   ^
```

This was pretty easy to do using `moveby.regex`:

```
{
    "key": "ctrl+alt+right",
    "when": "editorTextFocus",
    "command": "moveby.regex",
    "args": {
        "regex": "\\s+|$",
        "properties": ["next", "start", "nowrap"]
    }
},
{
    "key": "ctrl+alt+left",
    "when": "editorTextFocus",
    "command": "moveby.regex",
    "args": {
        "regex": "\\s+|^",
        "properties": ["prev", "end", "nowrap"]
    }
},
```

My next goal was to add the selection to the movement, which was more difficult than I thought it would be (I had the movement, I just wanted to add the selection bit; the regexes didn't quite work the same way, though). I got the extend selection forward to work using this:

```
{
    "key": "shift+ctrl+alt+right",
    "when": "editorTextFocus",
    "command": "selectby.regex",
    "args": {
        "forward": "\\s+|$",
        "forwardInclude": true
    }
},
```

though without the `forwardInclude: true` it didn't work, and it's not really what I wanted. But I figured I could live with it, so I added in what I thought would be the analagous extend selection backward keybinding:

```
{
    "key": "shift+ctrl+alt+left",
    "when": "editorTextFocus",
    "command": "selectby.regex",
    "args": {
        "backward": "\\s+|^",
        "backwardInclude": false
    }
},
```

Invoking this even once, though, causes all of the SelectBy keybindings to stop working, and VS Code itself hangs when I try to exit (I have to force quit, which is essentially sending a kill -9 to the process).

**Comment by rioj7** [comment]
@NorthboundTrain 

The reason is that your `backward` regex can match an empty string (`^`), you might have added it to select line begin but that will not work because the whole file is 1 string for the search, but looks like it works because `\r` and `\n` are also part of `\s`.

An empty match caused an infinite loop and a need to kill VSCode, I have fixed this situation.

I have added 2 properties: `forwardAllowCurrentPosition` and `backwardAllowCurrentPosition` so you can select if you want to add the whitespace to the extension.

Example for the forward extension
```
{
    "key": "shift+ctrl+alt+right",
    "when": "editorTextFocus",
    "command": "selectby.regex",
    "args": {
        "forward": "\\s+",
        "forwardInclude": false,
        "forwardAllowCurrentPosition": false
    }
},
```

**Comment by NorthboundTrain** [comment]
Awesome, thank you!
