### ISSUE TITLE
Deselect if selection currently active when going in opposite direction

### ISSUE THREAD

**Issue by EnderShadow8** [rioj7/select-by#13]
When using the native VSCode select/deselect via shift+arrow, if the cursor is currently selecting towards the right and I press shift+left then it deselects one character. I would like this behaviour with `selectby.regex` like so:

Bad (current):

https://user-images.githubusercontent.com/69184571/153689503-9bcd1902-2561-4a55-8f6c-64d74459b255.mp4

Good:

https://user-images.githubusercontent.com/69184571/153689508-32b1e18b-eaba-47f9-8129-976128b59c95.mp4

**Comment by rioj7** [comment]
@EnderShadow8 From the video's I'm unable to determine what you do and what you expect.

Describe in detail what you do, select XXXX, press key YYYY, and what is your `selectby.regex` parameters.

**Comment by EnderShadow8** [comment]
The regex is irrelevant.

If I start with a cursor, extend the selection right and then left, I want them to cancel each other out instead of extending in both directions. Essentially the default behaviour of ctrl+shift+left and ctrl+shift+right, where selecting in one direction and the other cancels out.

**Comment by rioj7** [comment]
@EnderShadow8 You still talk in general terms.

Please give an example with exact key presses and what you expect and what you see and what it has to do with `selectby.regex` if you say the regex is irrelevant.

**Comment by EnderShadow8** [comment]
Example:

Regex: `.` (one character)

Text: (`|`) is cursor
```
as|df
````

selectby next x2:

```
as|df|
````

selectby prev (expected)
```
as|d|f
```
actual:
```
a|sdf|
```

Is this example helpful?

**Comment by rioj7** [comment]
@EnderShadow8 The fact that you talk about `next` and `x2` means you use `moveby.regex`. But this does not select text.

`selectby.regex` uses arguments like `forward` and `backward`, ....

So it is also important to see the exact keybinding/setting you use for the command.

`selectby.regex` was designed to extend the current selection on both sides or one side of the selection. `forward` applies to the `end` of the selection, `backward` is for the `start` of the selection (character position relative to start of file). That is the reason that when you do `backward` (prev, wrong naming) the character `s` is added to the selection.

I can add additional properties, like `forwardShrink` and `backwardShrink`, to use a regex to reduce the selection on that side instead of Expand.

This can lead to expanding the selection if the shrink goes beyond the position on the other side (the forward and backward regex can be different)

**Comment by EnderShadow8** [comment]
> The fact that you talk about next and x2 means you use moveby.regex. But this does not select text.
> selectby.regex uses arguments like forward and backward

My bad, I wrote this off memory.

> I can add additional properties, like forwardShrink and backwardShrink, to use a regex to reduce the selection on that side instead of Expand.
> This can lead to expanding the selection if the shrink goes beyond the position on the other side (the forward and backward regex can be different)

Yes, that's the behaviour I'm looking for. Thanks

**Comment by rioj7** [comment]
@EnderShadow8 try v1.12.0

**Comment by EnderShadow8** [comment]
Testing this in isolation works, but when I tried to incorporate it into my config, I ran into a problem. Using the forwardShrink property doesn't prevent the expansion of selection in the backward direction and vice versa. I want to make it either shrink or expand, but not both at once. (See my original video)

Demo:

https://user-images.githubusercontent.com/69184571/155934608-e964ce26-7a2e-4cd2-a753-86d19a261d35.mp4

**Comment by rioj7** [comment]
@EnderShadow8 You talked about the behavior of the standard Select - Grow and Shrink - If you continue to use `Shift-ArrowLeft` the selection will be expanded on the start side of the selection, from nothing selected to a selection with the active before the anchor.

**Comment by EnderShadow8** [comment]
Watch the video, the selection is not shrinking but rather just moving along, since it both shrinks and expands at the same time.

This is different from standard select, where if the cursor moves towards the anchor it shrinks, otherwise it grows, but not both at once.

**Comment by rioj7** [comment]
@EnderShadow8 (Oops a few days skipped [Horizon on PS]) Can you show me the settings you used that has this slide effect.

**Comment by EnderShadow8** [comment]
No problem, take your time :)

Do you want me to open a new issue?

```json
// keybindings.json
{"key": "ctrl+shift+left", "command": "selectby.regex", "when": "textInputFocus", "args": {
    "backward": "\\n|(\\w+|([^\\w])\\2|.) *",
    "forward": "\\n| *(\\w+|([^\\w])\\2|.)",
    "forwardShrink": true,
  }}
```

**Comment by rioj7** [comment]
@EnderShadow8 `backward` and `forward` are done independent of each other. So if you include a `backward` regex in a `forwardShrink` operation the start of the selection will change.

Your goal is to emulate the behavior of `cursorWordLeftSelect` and `cursorWordEndRightSelect`, the extend/shrink selection by word, but now by regex.

The behavior moves the position of `active` (cursor) left or right a word. `selectby.regex` only uses `start` and `end`. A better name for this command would be `selectby.start.end.by.regex`.

Not to complicate the configuration of `selectby.regex` it would be best to add a new command: `selectby.active.by.regex`

It has the following parameters:

* `regex`: what to search for
* `direction`: with values `left` or `right`, in which direction to move active

I don't think that moving `anchor` will be useful or I have to add a command `selectby.active.anchor.by.regex` with parameters:

* `active.regex`: what to search for
* `active.direction`: with values `left` or `right`, in which direction to move active
* `anchor.regex`: what to search for
* `anchor.direction`: with values `left` or `right`, in which direction to move anchor

There will always be somebody with a weird use case for this.

**Comment by EnderShadow8** [comment]
> The behavior moves the position of active (cursor) left or right a word. selectby.regex only uses start and end. A better name for this command would be selectby.start.end.by.regex.

Sounds like that's what I'm looking for. Many thanks

**Comment by rioj7** [comment]
@EnderShadow8 look at v1.13.0 and command [`selectby.anchorAndActiveByRegex`](https://github.com/rioj7/select-by#select-by-anchor-and-active-by-regex)
