### ISSUE TITLE
settings.json entry for moveby.regex

### ISSUE THREAD

**Issue by blueray453** [rioj7/select-by#16]
I have lines like

```
gsettings set org.gnome.settings-daemon.plugins.media-keys.logout @as []

gsettings set org.gnome.mutter.keybindings.toggle-tiled-left @as []

gsettings set org.gnome.mutter.keybindings.toggle-tiled-right @as []

gsettings set org.gnome.settings-daemon.plugins.media-keys.screenshot @as []

gsettings set org.gnome.settings-daemon.plugins.media-keys.window-screenshot-clip @as []

gsettings set org.gnome.settings-daemon.plugins.media-keys.area-screenshot-clip @as []

gsettings set org.gnome.settings-daemon.plugins.media-keys.screenshot-clip @as []

gsettings set org.nemo.window-state.maximized true

gsettings set org.gnome.Totem.subtitle-encoding 'UTF-8'
```

I have put cursor on the beginning of each line. Now I want to go to the last `.` of each line. The regex for this is `\.(?!.*\.)`. I do not want keybinding. I want to find the item from command palate. How can I make an entry in `settings.json` file?

To be specific, I can not build few regex. If I can save the regex in config and call from command palate then it will be great. For example: I want to name this `Go to Last Dot`

**Comment by rioj7** [comment]
@blueray453 It's on the TODO list (moveby from Cmd Palette) I will implement this in the next few days

**Comment by rioj7** [comment]
@blueray453 Have a try with v1.16.0

**Comment by blueray453** [comment]
I have checked. Copy pasted the code from the [documentation](https://github.com/rioj7/select-by#move-by-regular-expression).

 ```
 "moveby.regexes": {
    "Go to Last Dot": {
      "regex": "\\.(?!.*\\.)",
      "properties": ["next", "start"]
    },
    "--Ask-- $(regex) next end": {
      "ask": true,
      "properties": ["next", "end"]
    },
    "--Ask-- $(regex) next start": {
      "ask": true,
      "properties": ["next", "start"]
    }
  }
```

Here, last two (`--Ask-- $(regex) next end`, `--Ask-- $(regex) next start`) works if I use `\.(?!.*\.)` when asked.

But the first one (`Go to Last Dot`) does not work.

**Comment by rioj7** [comment]
@blueray453 

If I try with your test text and the given setting it works.

Do you see the option: `Go to Last Dot`?

Do you have the double \ in the regex?

What if you add the following property to `Go to Last Dot`:
```
"debugNotify": true
```
Do you see a `bug` icon next to the Pick List option?
You get an information message, what does it tell you?

**Comment by blueray453** [comment]
Do you see the option: Go to Last Dot?
yes

Do you have the double \ in the regex?
yes

`"debugNotify": true`

Do you see a bug icon next to the Pick List option?
yes

You get an information message, what does it tell you?
`{"regex":"\\.(?!.*\\.)","properties":["next","start"],"debugNotify":true}`

**Comment by blueray453** [comment]
It is actually working now. Thank you very much.

**Comment by rioj7** [comment]
@blueray453  The notify message can show you how VSC merges the different `settings.json` files. If you have defined `moveby.regexes` in different `settings.json` files you can end up with unwanted properties if you don't explicitly override them if needed.

Do you know why the first test did not work? Could be a typo or something other small.

**Comment by blueray453** [comment]
Yesterday, it seemed to be not working. I checked multiple times before reporting. It was not a typo because I copy pasted. And today I did not change anything other than adding `"debugNotify":true`.

I do not think there is any bug. I think I made some mistake yesterday. Or maybe there was some issue with my computer. I am checking it now again. No issues.
