### ISSUE TITLE
Select next instance of selection, at each selection?

### ISSUE THREAD

**Issue by GanerCodes** [rioj7/select-by#17]
I wonder how I can construct a command that, when pressed, acts like "add selection to next find match" but for every selection simultaneously. The attached video is some of the current behavior I would like to avoid, the the image is what I would like to create

![image](https://user-images.githubusercontent.com/34655998/176786673-e47545af-a204-463e-a129-5114438a0cb7.png)

https://user-images.githubusercontent.com/34655998/176786519-50f9bb46-6ff9-4f8b-9a05-7becfb9b14d7.mp4

**Comment by rioj7** [comment]
@GanerCodes 

* should the search be only on the current line
* what should happen if you execute the command another time, there is no more `test` on the same line
* should only the last selection of the line be used to search for a new selection

Currently `selectby.regex` does not support Multi Cursor yet, not impossible but I have to implement it.

**Comment by GanerCodes** [comment]
1. No, simply selects the next one and stops when no results are found or it runs into the next selection
2. Nothing
3. No, it takes place at all selections regardless of newlines

That would be awesome

**Comment by rioj7** [comment]
@GanerCodes Try v1.19.0 the commandID to use in a key binding is `selectby.addSelectionToNextFindMatchMultiCursor`

You can also search the Command Palette for: **Add Selection To Next Find Match - Multi Cursor**

I forgot about this issue and then realized it should be done outside `selectby.regex`.

**Comment by GanerCodes** [comment]
Absolute king-tier work, thanks so much!
