### ISSUE TITLE
`selectby.regex` always shows QuickPick list

### ISSUE THREAD

**Issue by zx8** [rioj7/select-by#18]
**VSCode version:** v1.69.2
**Extension version:** v1.16.0

---

I have the following keybind:

```json
{
  "key": "alt+,",
  "when": "editorTextFocus",
  "command": "selectby.regex",
  "args": [
    "Expand Selection By Whitespace"
  ]
}
```

And the following definition in my settings:

```json
"selectby.regexes": {
  "Expand Selection By Whitespace": {
    "backward": "\\s",
    "backwardInclude": false,
    "forward": "\\s",
    "forwardInclude": false
  }
}
```

Previously, when I pressed `alt+,`, the keybinding would select the text immediately. Recently, something has changed and the QuickPick list always shows up, so I have to press an additional keybind (i.e. `<enter>`) to accept the selection and run the command:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/8544900/180818083-7c1bdd51-35c8-485f-8718-4640c5c26faf.png">

Is this a bug, or am I doing something wrong?

---

**[EDIT]** _~I just realized that I enabled a new feature in VSCode v1.69+ which maybe be the reason for this new behaviour:~_

Never mind, I disabled it and it's still happening! 

```
"window.commandCenter": true
```

**Comment by rioj7** [comment]
@zx8 try v1.16.1 fixed a small refactor bug
