### ISSUE TITLE
Feature request: allow selectby.pasteClipboard to work without pre-existing selection

### ISSUE THREAD

**Issue by certainlyakey** [rioj7/select-by#21]
Hi, thanks for the great plugin! 

I was wondering if it would be possible to make `selectby.pasteClipboard` be able to work without anything preselected, but just to insert-and-select the clipboard contents at current cursor. 

For me one of the use cases is Markdown, where i often paste something and want it to immediately be selected in order to apply some inline markup to the pasted text (eg backticks, quotes, paste a link over it, etc). 

For now i work it around by pre-selecting a space char, but if you are at the total end of the file you don't even have that commodity. 

Thanks in advance!

**Comment by rioj7** [comment]
@certainlyakey  I looked a the source code and can not find a reason why you should have something selected first.

I tried the command at different locations in a file and it works as expected. Also if the cursor is at the end of the file.

Can you give a detailed (step by step) instruction of a case where it does not work for you.

* what is the file content
* what is in the clipboard
* where is the cursor

**Comment by certainlyakey** [comment]
Coming back after almost a year, sorry 😄

So imagine a very simple file called `text.txt` (attached) with this contents: `something experience official`. The contents of the clipboard is the word `framework`. Let's consider two use cases:

A. I want to replace an existing selection with the contents of the clipboard and have it still selected. I select a word (eg. the first word `something`), then execute `selectBy.pasteClipboard` through the command palette, the command works as expected: the word `something` is replaced with `framework`, and that word is selected. The text now looks like this: `[framework]! experience official` (where `[]` denotes selection and `!` denotes cursor position).

B. I want to insert the contents of my clipboard after the word `something` and have the inserted text selected. I place my cursor after the word `something` (nothing is selected!), execute `selectBy.pasteClipboard`. 
What I would like to have: the word `framework` is inserted and gets selected. The text would look like this: `something [framework]! experience official`. 
What happens at the moment: The word framework gets inserted, nothing gets selected. The text looks like this: `something framework! experience official`. 
[text.txt](https://github.com/user-attachments/files/16740326/text.txt)

**Comment by rioj7** [comment]
@certainlyakey they must have changed the behavior of the `TextEditorEdit` in case nothing is selected.

An empty selection is a selection of 0 length, so why change the code to do different things.

On an older version of VSC it behaves as expected. On v1.90 I can recreate the issue.

The problem for a solution is with the `TextEditor::edit` method. It returns:

> A promise that resolves with a value indicating if the edits **could** be applied

"could be applied" means that there are no overlapping regions and other stuff.

I have no clue if the edits **are** applied when the Promise resolves. Everything in VSC is done async. It could be that the edits are on some queue to be applied later.

**Comment by rioj7** [comment]
@certainlyakey According to an [issue at vscode-doc](https://github.com/microsoft/vscode-docs/issues/7524) jrieken (vscode dev team) responds with:

> resolved promise true => edits are applied

implemented in v1.20.1, need to test on new VSC version before I publish.

**Comment by certainlyakey** [comment]
@rioj7 excellent, thanks a lot for implementing it! I will be glad to test it out

**Comment by rioj7** [comment]
@certainlyakey tested with v1.92.2 on Linux and published

**Comment by certainlyakey** [comment]
Works great on MacOs 13.6.9.
