### ISSUE TITLE
Feature request: move cursor to next 'section'

### ISSUE THREAD

**Issue by rick3rt** [rioj7/select-by#3]
Not an issue, but a feature request :) 

Do you think it is possible to move the cursor through the file based on a regex search (i.e. section in Matlab)? I tried to look into the VScode extension api myself, but my non-existing knowledge of JS programming made it impossible to get something to work. Would be much appreciated! 

I am enjoying the select-by extension every day, so thanks again 👍

**Comment by rioj7** [comment]
Use v0.5.0, see the doc for how to use

**Comment by rick3rt** [comment]
Awesome, Thanks! Is there a possibility to scroll along with the moving cursor?

**Comment by rioj7** [comment]
@rick3rt : see v0.5.1, use setting to change behavior, see doc

**Comment by rick3rt** [comment]
Thanks a million, I got it all setup now, it works perfect!
