### ISSUE TITLE
More regexN commands

### ISSUE THREAD

**Issue by certainlyakey** [rioj7/select-by#4]
Hi! Thanks for the great plugin. It solved so many of my selection needs. 

I use it to move (by subword), expand/shrink selection backwards by character, subword, and find word under cursor. As opposed to the built-in VSC functionality, the plugin allows to do this more granularly...

But the problem now is — I ran out of `selectby.regexN` commands 😁

Could you add 5 more? 

Thanks a lot!

**Comment by rioj7** [comment]
I will add a few more or make a way to add an unlimited number.

**Comment by certainlyakey** [comment]
Thank you! 🙂

**Comment by rioj7** [comment]
use v0.6.0. Read the ReadMe for the changes
