### ISSUE TITLE
How to use a named command in a macro - `args`?

### ISSUE THREAD

**Issue by ArturoDent** [rioj7/select-by#5]
I would like to set up the `selectby` command by name (rather than `regex1, regex2, etc,`) and then use it in a macro in a series of commands.  See, e.g., https://stackoverflow.com/questions/61382609/vs-code-shortcut-to-select-or-remove-block-comment-with-no-text-selected/61414740#61414740

But there I had to use the `regex1` instead of giving it a name like:

   "BlockCommentSelect": {
    // "regex1": {
      "backward": "\/\\*",
      "forward": "\\*\/",
      "forwardInclude": true,
      "backwardInclude": true,
      "showSelection": true
    }
  },

because I couldn't get it work in the macro where the name must be an argument, as in:

  {
      "command": "multiCommand.BlockCommentOff",
      "sequence": [
        //  "selectby.regex1",   // easy, works but not descriptive
         {
           "command": "selectby.regex",
           "args": "[\"BlockCommentSelect\"]"   // doesn't work
           //  "args": "BlockCommentSelect"          // doesn't work
        }
        "editor.action.blockComment"
      ]
    },

Thank you.

**Comment by rioj7** [comment]
The argument of the command is an array of strings of length 1.

Try this

```
{
    "command": "multiCommand.BlockCommentOff",
    "sequence": [
        { "command": "selectby.regex", "args": ["BlockCommentSelect"] },
        "editor.action.blockComment"
    ]
}
```

**Comment by ArturoDent** [comment]
Thank you.  That works.
