### ISSUE TITLE
go to next empty line `^$`

### ISSUE THREAD

**Issue by ArturoDent** [rioj7/select-by#7]
I'm just trying to go to next/previous **empty line**.  So I thought the regex `^$` with `m` flag would work.

    "goToEmptyLine": {
      "flags": "m",
      "moveby": "^$",
    },

  ```
{
    "key": "alt+y",
    "when": "editorTextFocus",
    "command": "moveby.regex",
    "args": ["goToEmptyLine", "moveby", "prev", "start"]
  },

  {
    "key": "alt+u",
    "when": "editorTextFocus",
    "command": "moveby.regex",
    "args": ["goToEmptyLine", "moveby", "next", "start"]
  },
```

But nothing happens.  

-------------

I fixed it.  Using this regex `^$\r?\n` or uninstall/re-install Select By - one of them fixed it.

**Comment by rioj7** [comment]
The program gets stuck in an endless loop. Fixed in version 0.7.2
