### ISSUE TITLE
Wrap the search with moveby

### ISSUE THREAD

**Issue by ArturoDent** [rioj7/select-by#8]
Is it possible to wrap the moveby command?  So that if you are below the search term and search `next` you will wrap beyond the end of the file and go to the first instance of the term.

This is to avoid having to have two keybindings, one for `next` and another for `prev`.

See https://stackoverflow.com/questions/62938935/bind-a-command-to-go-to-a-specific-symbol-in-vs-code/62939964?noredirect=1#comment111477390_62939964 for example where usage of selectBy was undesirable for this reason.

**Comment by rioj7** [comment]
v0.7.4: A few nasty cases took me a bit more time. There is now an additional parameter `"wrap"` for `moveby`
