### ISSUE TITLE
Skip forward to bypass leading spaces?

### ISSUE THREAD

**Issue by cniggeler** [rioj7/select-by#9]
**EDIT:** I have been looking at the Select By Javascript code; unless I'm missing something, it's not possible to "stack" actions, so perhaps an additional action like "advance" would be in order. So if you use "moveby" you can then use "advance" to advance the cursor to the specified location. In my case, it could look line
` "moveToFileNameStart": {`
&nbsp;&nbsp;&nbsp;`        "flags": "m",`
&nbsp;&nbsp;&nbsp;`        "moveby": "^|(?<=, )",      // move to start of line or to ","`
&nbsp;&nbsp;&nbsp;`        "advance": "\\w"               // advance to first non-space character`
`      },
`

What do you think?

<hr>

Hi, I'm currently working with you and Mark at stackoverflow, topic: "VSCode hyperlink between results in one file to different file:line". Mark is using a combo of multi-command and Select By which holds promise for adding an additional layer of indirection. Anyway, he uses `"moveby": "^|(?<=, )"` to get to the start of the line or ',' as in my original post there can be >1 result on a line. I've been able to generalize his approach by adding ${relativeFileDirname} to the send sequence, BUT what's happening is, there are embedded spaces between the start of the line and the start of the filename. I've not been able to find a sequence of Select By instructions to move from the start of the line to the start of the filename, so I get a PowerShell command like this: 
`code -g c:\path\to\                             file.c:123`
(There are many more spaces, but I can't get this text input tool to show them, but even one suffices). How can I remove those leading spaces? Thanks!

**Comment by rioj7** [comment]
If you change the regex to
```
"moveby": "^ *|(?<=, *)"       // move to start of line or to ","
```
it will skip the possible spaces at the beginning of the line and multiple spaces after the `,`.

**Comment by cniggeler** [comment]
Hi, I tried something like that before without success. When I put exactly the suggestion above,  the Terminal output looks like this:
`PS C:\Users\Chris> code -g c:\path\to\`
`PS C:\Users\Chris>      `&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`   file.c:123 `
`file.c:123 : The term 'file.c:123' is not recognized as the name of a cmdlet, ...`
It seems to introduce a newline?
<hr>
**Update:** if I just highlight the "123" portion of the string, it works. But if I highlight all the string (e.g., file1.c@123) I get the problem above. In Mark's gif example he does just that apparently with success, the difference being he was using relative paths and I am prepending a path in the send sequence that calls "code"... I don't mean for you to debug someone else's code, so can you tell me if that's the expected behavior with the moveby: and an entire file@line string is selected?

**Comment by rioj7** [comment]
You don't need to select anything before you call the macro from Mark. Just place the cursor somewhere **inside** the `file@line` and then call the macro.

If you select the whole `file@line` the search uses the start of the selection as the test location and finds the location of the regex that is **before** or **after** this test location. The test location is the beginning of the `file@line` so you search for the file that is before/after the one your cursor/selection is at.

To debug what is happening you can remove parts of the macro sequence and see what is selected before you send it to the terminal.

**Comment by ArturoDent** [comment]
I updated the answer on SO and was able to simplify it significantly.  Spaces before the first file on a line are no problem. 

Yes, don't select anything, just put the cursor anywhere within the `filename@linenumber` and it will work.  You can even put the cursor before the first file or right after the last file and it will work.

I also added single quotes around the directory name and file name in case those may have spaces within them as in 

`some folder/ some file.c`

You can also add the `"interval": <some milliseconds here>` option to the multi-command macro to watch it go through the steps one by one slowly.  Like `"interval": 2000,`  so each step takes two seconds.

**Comment by cniggeler** [comment]
> Yes, don't select anything

In your animated gif, I mistook you demonstrating something for an actual selection :-) The updated version on SO is working well, with the exception of the enclosing tickmarks as described in the comments there. Very minor fix.

Since my problem seems to have been operator error, I will be closing out this bug here. Thanks to both of you for your assistance and experience!
